### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by BRYNHILDRINTHEDARKNESS** [JMBQ/dump-games#1]
能否提供一下联系方式？有问题探讨，QQ和TG都可以

**Comment by JMBQ** [comment]
可以来这找我，寂灭不去

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 可以来这找我，寂灭不去
> https://mega.nz/chat/Iw0VSaab#sWAAwGvtzL9b0jRUGAuo0w

能不能换种联系方式，这种有点麻烦

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 可以来这找我，寂灭不去 https://mega.nz/chat/Iw0VSaab#sWAAwGvtzL9b0jRUGAuo0w

进去了，没找着你

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 可以来这找我，寂灭不去 https://mega.nz/chat/Iw0VSaab#sWAAwGvtzL9b0jRUGAuo0w

添加了 你同意，寂灭不尽
