### ISSUE TITLE
genshin impact 3.2

### ISSUE THREAD

**Issue by Saint-Theana** [JMBQ/dump-games#2]
global version 3.2

zygisk-il2cppdumper

error: Failed to initialize il2cpp api.

**Comment by JMBQ** [comment]
那肯定是隐藏API了，有空瞧下

**Comment by Saint-Theana** [comment]
> That il2cpp API must be hidden, I'll take a look when I have time

不改成英文其实也可以的

**Comment by Saint-Theana** [comment]
> 弄了官网的3.2 ，导出API倒是能打印出来，就是这货貌似删掉了il2cpp_domain_get_assemblies？隐藏的话肯定存在，但我凭着各种调用和特征，把大部分API都捕捉了，唯独没有找到关键的il2cpp_domain_get_assemblies，要么魔改掉特征了，要么彻底消失？ 我试图用代码重建该API也不行，运行至获取image->name必崩，至此，il2cppdumper完败于它
> 
> ```
> 直接获取3.2所有导出API
> void *handle1 = dlsym(il2cpp_handle, "il2cpp_get_api_table");
> if (handle1) {
>         //3.2.0
>         LOGI("handle1: %p", handle1);
>         unsigned long long s[177];
>         memset(s, 0, sizeof(s));
>         auto sub = (void *(*)(unsigned long long *))handle1;
>         sub(s);
>         for (int i = 0; i < 177; ++i) {
>             LOGI("s[%d] = 0x%llx", i, s[i] - il2cpp_base);
>         }
> }
> 
> //篇幅所限，仅部分
> address[0] = 0x42303f4
> address[1] = 0x423042c
> address[2] = 0x4230430
> address[3] = 0x4230434
> address[4] = 0x4230438
> address[5] = 0x423043c
> address[6] = 0x423044c
> address[7] = 0x4230450
> address[8] = 0x4230454
> address[9] = 0x4230458		il2cpp_get_corlib
> address[10] = 0x423045c
> address[11] = 0x4230460
> address[12] = 0x4230464
> address[13] = 0x4230468
> address[14] = 0x423046c
> address[15] = 0x4230470
> address[16] = 0x4230474
> address[17] = 0x4230478
> address[18] = 0x423047c
> address[19] = 0x4230480
> address[20] = 0x4230484
> address[21] = 0x423048c
> address[22] = 0x4230490		il2cpp_assembly_get_image
> ```
> 
> 既然魔改这么严重，我推荐使用frida_il2cpp 来dump，它需要到的il2cpp API很少

global版本，不是cn版本
