### ISSUE TITLE
绯染天空

### ISSUE THREAD

**Issue by AotoriChiaki** [JMBQ/dump-games#3]
请求dump一下绯染天空这个游戏，情况表现为打开Zygisk-Il2CppDumper模块的情况下打开游戏，什么都没有发生，没有dumping...提示

**Comment by JMBQ** [comment]
可以dump，失败是你自己的原因

**Comment by AotoriChiaki** [comment]
后来我从/data/data拿到libil2cpp.so然后dump出来了……但是用Zygisk就不知道为啥不行，可能是我用模拟器的原因？

还想请问一下Zygisk模块代码里LOGD LOGI这种log会输出到哪里，我随便写了点log试了一下发现magisk的日志菜单里面什么也没有输出

**Comment by JMBQ** [comment]
用as看
