### ISSUE TITLE
大佬抽空分析下斗诡这个游戏吧。谢谢

### ISSUE THREAD

**Issue by 1034205079** [JMBQ/dump-games#5]

**Comment by JMBQ** [comment]
有空就看下

**Comment by JMBQ** [comment]
我发的这3刀已经足够虐斗诡了，你真是个不爱学习的家伙

**Comment by JMBQ** [comment]
> > 我发的这3刀已经足够虐斗诡了，你真是个不爱学习的家伙
> 
> 见笑了大佬，我是个改u3d游戏的爱好者。因为不是it从业者，有些东西确实看不懂，所以才有此问。不知道大佬是否可以出个视频教学吗？ida那个我会操作，就是后面您写的脚本我就抓虾了。

我觉得文章已经说得很清楚了，代码不是脚本，是c/c++源码，需要as来编译，你哪里不明白

**Comment by 1034205079** [comment]
> > > 我发的这3刀已经足够虐斗诡了，你真是个不爱学习的家伙
> > 
> > 
> > 见笑了大佬，我是个改u3d游戏的爱好者。因为不是it从业者，有些东西确实看不懂，所以才有此问。不知道大佬是否可以出个视频教学吗？ida那个我会操作，就是后面您写的脚本我就抓虾了。
> 
> 我觉得文章已经说得很清楚了，代码不是脚本，是c/c++源码，需要as来编译，你哪里不明白

好的，谢谢大佬。请问我是用AS编译成压缩包然后安装到面具里吗？是不是和p神的那个一样呀？😂😂

**Comment by 1034205079** [comment]
> > > > > 我发的这3刀已经足够虐斗诡了，你真是个不爱学习的家伙
> > > > 
> > > > 
> > > > 见笑了大佬，我是个改u3d游戏的爱好者。因为不是it从业者，有些东西确实看不懂，所以才有此问。不知道大佬是否可以出个视频教学吗？ida那个我会操作，就是后面您写的脚本我就抓虾了。
> > > 
> > > 
> > > 我觉得文章已经说得很清楚了，代码不是脚本，是c/c++源码，需要as来编译，你哪里不明白
> > 
> > 
> > 好的，谢谢大佬。请问我是用AS编译成压缩包然后安装到面具里吗？是不是和p神的那个一样呀？😂😂
> 
> 本来就一样，文章只是深扒某些不听话的游戏

好的谢谢大佬，我回去再研究下。我其实还遇到些游戏，用了p神的zgysikdump出来的dump.cs文件，它只有一些没用的代码。例如奇门之上这个游戏，之前这个游戏直接dump出来所有的offset 现在很多都隐藏了。不知道用了什么手段😂😂

**Comment by 1034205079** [comment]
大佬，斗诡我dump出来了，就是没有用信息，我看是Assembly-CSharp.dll没dump出来。不知道该如何解决，求教
![image](https://github.com/JMBQ/dump-games/assets/47485084/7a84cc97-e4ca-4570-96cd-89e64fdabe7d)

**Comment by JMBQ** [comment]
如何修改要自己摸索
