### ISSUE TITLE
能帮忙看看崩坏3官网6.9版吗？

### ISSUE THREAD

**Issue by mailzyf** [JMBQ/dump-games#6]
也是隐藏了几乎所有的il2cpp的api，搜索libunity.so只找到.il2cpp_get_api_table

**Comment by JMBQ** [comment]
不是提示很明显了吗，找到这个get方法，弄明白它的api获取方式就行了

**Comment by 2720659174** [comment]
楼主，能不能也出一期崩坏的教程感觉需要的人蛮多的，我也想学习一下

**Comment by JMBQ** [comment]
那就统一回复下，在libil2cpp.so里找到这个get_api_table方法，见名知义，仔细分析它的逻辑，从而获取被隐藏的api。

看不懂这个方法，不会分析，那就没办法了

**Comment by JMBQ** [comment]
com.miHoYo.enterprise.NGHSoD v6.9.0

这是由代码自动打印出来的API偏移，稍微核对了几个，都对，并没有全部核对
别找我要名称，我还没打印

a6696c0
cbcd3a0
cbcd3a8
cbcd530
cbcd65c
5d2a380
cbcdb74
5d2a8cc
cbcdfd0
cbce040
cbce0b0
cbce1e4
932b680
a8fa83c
9d2d73c
989c1f8
9c56bc8
9c56c9c
9c569d8
9c56a44
a036a98
a036ba8
a036c84
b549ba0
b549c70
5d2a328
a2beaa0
a2beb60
5d2a3c8
a2e3500
a2e3338
a2e3560
a2e3404
a2e27e4
5d2a6a4
5d2a310
a2e29f8
9e5de70
989bf48
989c03c
97e8818
9d51204
9c5f084
9c5efa8
9c5edbc
97e8990
9c5fb60
9c5fa88
9c5f890
9b690b0
93186bc
98bf504
9b653fc
9b346e8
9a424a4
a5bd428
9a686a4
b53b31c
9d1a164
a8ed2e8
9d50984
a044554
b54ade8
5d2a398
a2eb844
a332f80
a55b09c
a55b1e0
a55b028
5d2a6f0
a55b03c
a55b1d4
a0a3544
a0a34bc
a0a34c0
a0a35ec
a0a35f0
a0a3604
5d2a714
986eb30
cefe0b4
cefe0bc
cefe0c4
cefe100
cefe1fc
cefe3f8
cefe4f0
cefe754
cefe840
cefe974
5d2a780
c6fcc14
c6fcc1c
c6fcc24
5d2a0f8
c6fcc70
c6fcd6c
c6fcfec
c6fd0e4
c6fd3cc
c6fd4b8
c6fd660
c6fd748
cbcd380
cbcd388
cbcd390
cbcd398
a388b4c
a388b5c
a388ee8
5d2a94c
9dc4f2c
9dc4f3c
5d2a624

**Comment by mailzyf** [comment]
再次感谢大神帮助，我再研究下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JMBQ/dump-games"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月13日(星期三) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JMBQ/dump-games] 能帮忙看看崩坏3官网6.9版吗？ (Issue #6)





 
com.miHoYo.enterprise.NGHSoD v6.9.0
 
这是由代码自动打印出来的API偏移，稍微核对了几个，都对，并没有全部核对
 别找我要名称，我还没打印
 
a6696c0
 cbcd3a0
 cbcd3a8
 cbcd530
 cbcd65c
 5d2a380
 cbcdb74
 5d2a8cc
 cbcdfd0
 cbce040
 cbce0b0
 cbce1e4
 932b680
 a8fa83c
 9d2d73c
 989c1f8
 9c56bc8
 9c56c9c
 9c569d8
 9c56a44
 a036a98
 a036ba8
 a036c84
 b549ba0
 b549c70
 5d2a328
 a2beaa0
 a2beb60
 5d2a3c8
 a2e3500
 a2e3338
 a2e3560
 a2e3404
 a2e27e4
 5d2a6a4
 5d2a310
 a2e29f8
 9e5de70
 989bf48
 989c03c
 97e8818
 9d51204
 9c5f084
 9c5efa8
 9c5edbc
 97e8990
 9c5fb60
 9c5fa88
 9c5f890
 9b690b0
 93186bc
 98bf504
 9b653fc
 9b346e8
 9a424a4
 a5bd428
 9a686a4
 b53b31c
 9d1a164
 a8ed2e8
 9d50984
 a044554
 b54ade8
 5d2a398
 a2eb844
 a332f80
 a55b09c
 a55b1e0
 a55b028
 5d2a6f0
 a55b03c
 a55b1d4
 a0a3544
 a0a34bc
 a0a34c0
 a0a35ec
 a0a35f0
 a0a3604
 5d2a714
 986eb30
 cefe0b4
 cefe0bc
 cefe0c4
 cefe100
 cefe1fc
 cefe3f8
 cefe4f0
 cefe754
 cefe840
 cefe974
 5d2a780
 c6fcc14
 c6fcc1c
 c6fcc24
 5d2a0f8
 c6fcc70
 c6fcd6c
 c6fcfec
 c6fd0e4
 c6fd3cc
 c6fd4b8
 c6fd660
 c6fd748
 cbcd380
 cbcd388
 cbcd390
 cbcd398
 a388b4c
 a388b5c
 a388ee8
 5d2a94c
 9dc4f2c
 9dc4f3c
 5d2a624
